// Copyright (c) 2025 Khramtsov Aleksei (seniorGolang@gmail.com).
// This file is subject to the terms and conditions defined in file 'LICENSE', which is part of this project source code.
package generator

const (
	// DefaultVersion версия плагина по умолчанию.
	DefaultVersion = "1.0.0"

	// DefaultLicense лицензия по умолчанию.
	DefaultLicense = "MIT"

	// DefaultModuleName имя модуля по умолчанию для core кода.
	DefaultModuleName = "tgp"

	// CoreDirName имя директории с общим кодом.
	CoreDirName = "core"

	// PluginsDirName имя директории с плагинами.
	PluginsDirName = "plugins"

	// GeneratedComment комментарий для сгенерированных файлов.
	GeneratedComment = "// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT."

	// GeneratedCommentYAML комментарий для сгенерированных YAML файлов.
	GeneratedCommentYAML = "# GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT."

	// DeployTypeNone значение deployType для отсутствия CI/CD.
	DeployTypeNone = "none"

	// DeployTypeGitLab значение deployType для GitLab CI/CD.
	DeployTypeGitLab = "gitlab"

	// DeployTypeGitHub значение deployType для GitHub Actions.
	DeployTypeGitHub = "github"

	// DefaultCategory категория плагина по умолчанию.
	DefaultCategory = "utility"

	// DefaultAuthor дефолтный автор плагина.
	DefaultAuthor = "Rick Sanchez <rick.sanchez@example.com>"

	// GitLabCIFileName имя файла конфигурации GitLab CI.
	GitLabCIFileName = ".gitlab-ci.yml"

	// GitHubWorkflowsDir имя директории для GitHub workflows.
	GitHubWorkflowsDir = ".github"

	// GitHubWorkflowsSubDir имя поддиректории для GitHub workflows.
	GitHubWorkflowsSubDir = "workflows"

	// GitHubDeployFileName имя файла конфигурации GitHub Actions.
	GitHubDeployFileName = "deploy.yml"

	// GoModFileName имя файла go.mod.
	GoModFileName = "go.mod"

	// GoSumFileName имя файла go.sum.
	GoSumFileName = "go.sum"

	// DistDirName имя директории для скомпилированных плагинов.
	DistDirName = "dist"

	// PluginJSONFileName имя файла манифеста плагина.
	PluginJSONFileName = "plugin.json"

	// PluginExtension расширение файла плагина.
	PluginExtension = ".tgp"

	// ChecksumExtension расширение файла checksum.
	ChecksumExtension = ".sha256"

	// JSONExtension расширение JSON файла.
	JSONExtension = ".json"

	// CoreWasmSubDir имя поддиректории wasm в core.
	CoreWasmSubDir = "wasm"

	// CoreExecSubDir имя поддиректории exec в core.
	CoreExecSubDir = "exec"

	// CoreHTTPSubDir имя поддиректории http в core.
	CoreHTTPSubDir = "http"

	// CoreDataSubDir имя поддиректории data в core.
	CoreDataSubDir = "data"

	// CorePluginSubDir имя поддиректории plugin в core.
	CorePluginSubDir = "plugin"

	// CoreNetSubDir имя поддиректории net в core.
	CoreNetSubDir = "net"
)
