// Copyright (c) 2025 Khramtsov Aleksei (seniorGolang@gmail.com).
// This file is subject to the terms and conditions defined in file 'LICENSE', which is part of this project source code.
package generator

const (
	// DefaultAuthor дефолтный автор плагина.
	DefaultAuthor = "Rick Sanchez <rick.sanchez@example.com>"
	// DefaultLicense лицензия по умолчанию.
	DefaultLicense = "MIT"
	// DefaultVersion версия плагина по умолчанию.
	DefaultVersion = "1.0.0"
	// DefaultCategory категория плагина по умолчанию.
	DefaultCategory = "utility"
	// DefaultModuleName имя модуля по умолчанию для core кода.
	DefaultModuleName = "tgp"

	// CoreDirName имя директории с общим кодом.
	CoreDirName = "core"
	// PluginsDirName имя директории с плагинами.
	PluginsDirName = "plugins"
	// CoreNetSubDir имя поддиректории net в core.
	CoreNetSubDir = "net"
	// CoreDataSubDir имя поддиректории data в core.
	CoreDataSubDir = "data"
	// CoreExecSubDir имя поддиректории exec в core.
	CoreExecSubDir = "exec"
	// CoreHTTPSubDir имя поддиректории http в core.
	CoreHTTPSubDir = "http"
	// CoreWasmSubDir имя поддиректории wasm в core.
	CoreWasmSubDir = "wasm"
	// CorePluginSubDir имя поддиректории plugin в core.
	CorePluginSubDir = "plugin"

	// DeployTypeNone значение deployType для отсутствия CI/CD.
	DeployTypeNone = "none"
	// DeployTypeGitLab значение deployType для GitLab CI/CD.
	DeployTypeGitLab = "gitlab"
	// DeployTypeGitHub значение deployType для GitHub Actions.
	DeployTypeGitHub = "github"

	// GeneratedComment комментарий для сгенерированных файлов.
	GeneratedComment = "// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT."
	// GeneratedCommentYAML комментарий для сгенерированных YAML файлов.
	GeneratedCommentYAML = "# GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT."

	// DistDirName имя директории для скомпилированных плагинов.
	DistDirName = "dist"
	// GoModFileName имя файла go.mod.
	GoModFileName = "go.mod"
	// GoSumFileName имя файла go.sum.
	GoSumFileName = "go.sum"
	// JSONExtension расширение JSON файла.
	JSONExtension = ".json"
	// PluginExtension расширение файла плагина.
	PluginExtension = ".tgp"
	// GitHubWorkflowsDir имя директории для GitHub workflows.
	GitHubWorkflowsDir = ".github"
	// ChecksumExtension расширение файла checksum.
	ChecksumExtension = ".sha256"
	// GitHubDeployFileName имя файла конфигурации GitHub Actions.
	GitHubDeployFileName = "deploy.yml"
	// GitHubWorkflowsSubDir имя поддиректории для GitHub workflows.
	GitHubWorkflowsSubDir = "workflows"
	// PluginJSONFileName имя файла манифеста плагина.
	PluginJSONFileName = "plugin.json"
	// GitLabCIFileName имя файла конфигурации GitLab CI.
	GitLabCIFileName = ".gitlab-ci.yml"
)
