// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package example

import "github.com/seniorGolang/tg/example/interfaces/types"

type requestExampleRPCTest struct {
	Arg0 int                    `json:"arg0"`
	User types.User             `json:"user"`
	Opts map[string]interface{} `json:"opts"`
}

type responseExampleRPCTest struct {
	Ret1 int    `json:"ret1"`
	Ret2 string `json:"ret2"`
}
