//go:build wasip1

// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.
package net

import (
	"net"
	"time"
)

// Conn представляет сетевое соединение через хост.
type Conn struct {
	id      uint64
	network string

	readDeadline  time.Time
	writeDeadline time.Time

	// readBufferPtr - указатель на кольцевой буфер для чтения (хост → WASM) (кэшируется)
	readBufferPtr    uint32
	readBufferPtrSet bool
	// readBufferDataSize - размер области данных ReadBuffer (кэшируется, константа)
	readBufferDataSize uint32
	// writeBufferPtr - указатель на кольцевой буфер для записи (WASM → хост) (кэшируется)
	writeBufferPtr    uint32
	writeBufferPtrSet bool
	// writeBufferDataSize - размер области данных WriteBuffer (кэшируется, константа)
	writeBufferDataSize uint32
}

var _ net.Conn = &Conn{}

// addr реализует net.Addr.
type addr struct {
	address string
}

func (a *addr) Network() (network string) {

	return NetworkTCP
}

func (a *addr) String() (str string) {

	return a.address
}

var _ net.Addr = (*addr)(nil)
