// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.
package i18n

func Msg(text string) (translated string) {
	translation, ok := translations[text]
	if !ok {
		translated = text
		return
	}
	translated = translation
	return
}
