// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.
package http

import nethttp "net/http"

// Типы

// Client представляет HTTP клиент.
type Client = nethttp.Client

// Transport представляет HTTP транспорт.
type Transport = nethttp.Transport

// Server представляет HTTP сервер.
type Server = nethttp.Server

// Handler представляет обработчик HTTP запросов.
type Handler = nethttp.Handler

// HandlerFunc представляет функцию-обработчик HTTP запросов.
type HandlerFunc = nethttp.HandlerFunc

// Request представляет HTTP запрос.
type Request = nethttp.Request

// Response представляет HTTP ответ.
type Response = nethttp.Response

// ResponseWriter представляет интерфейс для записи HTTP ответа.
type ResponseWriter = nethttp.ResponseWriter

// Header представляет HTTP заголовки.
type Header = nethttp.Header

// Cookie представляет HTTP cookie.
type Cookie = nethttp.Cookie

// ServeMux представляет HTTP мультиплексор запросов.
type ServeMux = nethttp.ServeMux

// FileSystem представляет файловую систему для HTTP файлового сервера.
type FileSystem = nethttp.FileSystem

// Dir представляет директорию для HTTP файлового сервера.
type Dir = nethttp.Dir

// File представляет файл для HTTP файлового сервера.
type File = nethttp.File

// Интерфейсы

// Flusher представляет интерфейс для принудительной отправки буферизованных данных.
type Flusher = nethttp.Flusher

// Hijacker представляет интерфейс для перехвата соединения.
type Hijacker = nethttp.Hijacker

// Pusher представляет интерфейс для HTTP/2 Server Push.
type Pusher = nethttp.Pusher

// RoundTripper представляет интерфейс для выполнения HTTP запросов.
type RoundTripper = nethttp.RoundTripper

// Функции

// ListenAndServeTLS запускает HTTPS сервер на указанном адресе.
var ListenAndServeTLS = nethttp.ListenAndServeTLS

// Serve запускает HTTP сервер на указанном listener.
var Serve = nethttp.Serve

// ServeTLS запускает HTTPS сервер на указанном listener.
var ServeTLS = nethttp.ServeTLS

// ServeContent отвечает на запрос используя содержимое из ReadSeeker.
var ServeContent = nethttp.ServeContent

// ServeFile отвечает на запрос содержимым файла.
var ServeFile = nethttp.ServeFile

// Handle регистрирует обработчик для указанного паттерна в DefaultServeMux.
var Handle = nethttp.Handle

// HandleFunc регистрирует функцию-обработчик для указанного паттерна в DefaultServeMux.
var HandleFunc = nethttp.HandleFunc

// StripPrefix возвращает обработчик, который удаляет указанный префикс из URL пути.
var StripPrefix = nethttp.StripPrefix

// FileServer возвращает обработчик, который обслуживает HTTP запросы с содержимым файловой системы.
var FileServer = nethttp.FileServer

// NotFound отвечает на запрос с кодом 404 Not Found.
var NotFound = nethttp.NotFound

// NotFoundHandler возвращает простой обработчик, который отвечает "404 page not found".
var NotFoundHandler = nethttp.NotFoundHandler

// Redirect отвечает на запрос с редиректом на указанный URL.
var Redirect = nethttp.Redirect

// RedirectHandler возвращает обработчик, который редиректит все запросы на указанный URL.
var RedirectHandler = nethttp.RedirectHandler

// Error отвечает на запрос с указанным кодом ошибки и сообщением.
var Error = nethttp.Error

// MaxBytesReader ограничивает размер тела запроса.
var MaxBytesReader = nethttp.MaxBytesReader

// NewRequest создаёт новый HTTP запрос.
var NewRequest = nethttp.NewRequest

// NewRequestWithContext создаёт новый HTTP запрос с контекстом.
var NewRequestWithContext = nethttp.NewRequestWithContext

// ReadRequest читает и парсит HTTP запрос из буфера.
var ReadRequest = nethttp.ReadRequest

// ReadResponse читает и парсит HTTP ответ из буфера.
var ReadResponse = nethttp.ReadResponse

// ParseHTTPVersion парсит версию HTTP из строки.
var ParseHTTPVersion = nethttp.ParseHTTPVersion

// ParseTime парсит время из HTTP заголовка.
var ParseTime = nethttp.ParseTime

// StatusText возвращает текстовое описание HTTP статус кода.
var StatusText = nethttp.StatusText

// DetectContentType определяет Content-Type по содержимому данных.
var DetectContentType = nethttp.DetectContentType

// CanonicalHeaderKey возвращает каноническую форму ключа заголовка.
var CanonicalHeaderKey = nethttp.CanonicalHeaderKey

// SetCookie устанавливает cookie в заголовках ответа.
var SetCookie = nethttp.SetCookie

// Get выполняет HTTP GET запрос.
var Get = nethttp.Get

// Head выполняет HTTP HEAD запрос.
var Head = nethttp.Head

// Post выполняет HTTP POST запрос.
var Post = nethttp.Post

// PostForm выполняет HTTP POST запрос с данными формы.
var PostForm = nethttp.PostForm

// NewServeMux создаёт новый HTTP мультиплексор запросов.
var NewServeMux = nethttp.NewServeMux

// Переменные

// DefaultClient представляет клиент по умолчанию.
var DefaultClient = NewClient()

// DefaultTransport представляет транспорт по умолчанию.
var DefaultTransport = NewTransport()

// DefaultServeMux представляет мультиплексор по умолчанию.
var DefaultServeMux = nethttp.DefaultServeMux

// Константы методов

const (
	MethodGet     = nethttp.MethodGet
	MethodHead    = nethttp.MethodHead
	MethodPost    = nethttp.MethodPost
	MethodPut     = nethttp.MethodPut
	MethodPatch   = nethttp.MethodPatch
	MethodDelete  = nethttp.MethodDelete
	MethodConnect = nethttp.MethodConnect
	MethodOptions = nethttp.MethodOptions
	MethodTrace   = nethttp.MethodTrace
)

// Константы статус кодов

const (
	StatusContinue                      = nethttp.StatusContinue
	StatusOK                            = nethttp.StatusOK
	StatusCreated                       = nethttp.StatusCreated
	StatusAccepted                      = nethttp.StatusAccepted
	StatusNonAuthoritativeInfo          = nethttp.StatusNonAuthoritativeInfo
	StatusNoContent                     = nethttp.StatusNoContent
	StatusResetContent                  = nethttp.StatusResetContent
	StatusPartialContent                = nethttp.StatusPartialContent
	StatusMultipleChoices               = nethttp.StatusMultipleChoices
	StatusMovedPermanently              = nethttp.StatusMovedPermanently
	StatusFound                         = nethttp.StatusFound
	StatusSeeOther                      = nethttp.StatusSeeOther
	StatusNotModified                   = nethttp.StatusNotModified
	StatusUseProxy                      = nethttp.StatusUseProxy
	StatusTemporaryRedirect             = nethttp.StatusTemporaryRedirect
	StatusPermanentRedirect             = nethttp.StatusPermanentRedirect
	StatusBadRequest                    = nethttp.StatusBadRequest
	StatusUnauthorized                  = nethttp.StatusUnauthorized
	StatusPaymentRequired               = nethttp.StatusPaymentRequired
	StatusForbidden                     = nethttp.StatusForbidden
	StatusNotFound                      = nethttp.StatusNotFound
	StatusMethodNotAllowed              = nethttp.StatusMethodNotAllowed
	StatusNotAcceptable                 = nethttp.StatusNotAcceptable
	StatusProxyAuthRequired             = nethttp.StatusProxyAuthRequired
	StatusRequestTimeout                = nethttp.StatusRequestTimeout
	StatusConflict                      = nethttp.StatusConflict
	StatusGone                          = nethttp.StatusGone
	StatusLengthRequired                = nethttp.StatusLengthRequired
	StatusPreconditionFailed            = nethttp.StatusPreconditionFailed
	StatusRequestEntityTooLarge         = nethttp.StatusRequestEntityTooLarge
	StatusRequestURITooLong             = nethttp.StatusRequestURITooLong
	StatusUnsupportedMediaType          = nethttp.StatusUnsupportedMediaType
	StatusRequestedRangeNotSatisfiable  = nethttp.StatusRequestedRangeNotSatisfiable
	StatusExpectationFailed             = nethttp.StatusExpectationFailed
	StatusTeapot                        = nethttp.StatusTeapot
	StatusMisdirectedRequest            = nethttp.StatusMisdirectedRequest
	StatusUnprocessableEntity           = nethttp.StatusUnprocessableEntity
	StatusLocked                        = nethttp.StatusLocked
	StatusFailedDependency              = nethttp.StatusFailedDependency
	StatusTooEarly                      = nethttp.StatusTooEarly
	StatusUpgradeRequired               = nethttp.StatusUpgradeRequired
	StatusPreconditionRequired          = nethttp.StatusPreconditionRequired
	StatusTooManyRequests               = nethttp.StatusTooManyRequests
	StatusRequestHeaderFieldsTooLarge   = nethttp.StatusRequestHeaderFieldsTooLarge
	StatusUnavailableForLegalReasons    = nethttp.StatusUnavailableForLegalReasons
	StatusInternalServerError           = nethttp.StatusInternalServerError
	StatusNotImplemented                = nethttp.StatusNotImplemented
	StatusBadGateway                    = nethttp.StatusBadGateway
	StatusServiceUnavailable            = nethttp.StatusServiceUnavailable
	StatusGatewayTimeout                = nethttp.StatusGatewayTimeout
	StatusHTTPVersionNotSupported       = nethttp.StatusHTTPVersionNotSupported
	StatusVariantAlsoNegotiates         = nethttp.StatusVariantAlsoNegotiates
	StatusInsufficientStorage           = nethttp.StatusInsufficientStorage
	StatusLoopDetected                  = nethttp.StatusLoopDetected
	StatusNotExtended                   = nethttp.StatusNotExtended
	StatusNetworkAuthenticationRequired = nethttp.StatusNetworkAuthenticationRequired
)
