//go:build !wasip1

// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.
package exec

import (
	"context"
	"io"
	"os/exec"
)

// Cmd представляет команду, готовую к выполнению.
// API аналогичен os/exec.Cmd, но скрывает WASM сложность.
// Для не-WASM сборок использует стандартный os/exec.Cmd.
type Cmd struct {
	cmd *exec.Cmd
}

// Command создает новую команду для выполнения.
// name - имя команды (например, "echo")
// arg - аргументы команды
func Command(name string, arg ...string) (cmd *Cmd) {

	execCmd := exec.Command(name, arg...)
	return &Cmd{
		cmd: execCmd,
	}
}

// CommandContext создает новую команду с контекстом для выполнения.
// ctx - контекст для отмены выполнения
// name - имя команды (например, "echo")
// arg - аргументы команды
func CommandContext(ctx context.Context, name string, arg ...string) (cmd *Cmd) {

	execCmd := exec.CommandContext(ctx, name, arg...)
	return &Cmd{
		cmd: execCmd,
	}
}

// Dir устанавливает рабочую директорию для команды.
func (c *Cmd) Dir(dir string) (cmd *Cmd) {

	c.cmd.Dir = dir
	return c
}

// Start запускает команду, но не ждет её завершения.
func (c *Cmd) Start() (err error) {

	return c.cmd.Start()
}

// Wait ждет завершения команды и возвращает ошибку, если команда завершилась с ненулевым кодом выхода.
func (c *Cmd) Wait() (err error) {

	return c.cmd.Wait()
}

// Run запускает команду и ждет её завершения.
func (c *Cmd) Run() (err error) {

	return c.cmd.Run()
}

// StdoutPipe возвращает pipe для чтения stdout команды.
// Должен быть вызван до Start().
func (c *Cmd) StdoutPipe() (reader io.ReadCloser, err error) {

	return c.cmd.StdoutPipe()
}

// StderrPipe возвращает pipe для чтения stderr команды.
// Должен быть вызван до Start().
func (c *Cmd) StderrPipe() (reader io.ReadCloser, err error) {

	return c.cmd.StderrPipe()
}

// ExitCode возвращает код выхода команды.
// Должен быть вызван после Wait().
func (c *Cmd) ExitCode() (exitCode int) {

	if c.cmd.ProcessState == nil {
		return -1
	}

	return c.cmd.ProcessState.ExitCode()
}
