//go:build wasip1

// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.
package net

//go:wasmimport net conn_dial
func conn_dial(networkPtr, networkLen, addressPtr, addressLen, connIDPtr uint32) uint64

//go:wasmimport net conn_dial_context
func conn_dial_context(deadline uint64, networkPtr, networkLen, addressPtr, addressLen, connIDPtr uint32) uint64

//go:wasmimport net conn_dial_tls
func conn_dial_tls(networkPtr, networkLen, addressPtr, addressLen, connIDPtr uint32) uint64

//go:wasmimport net conn_dial_tls_context
func conn_dial_tls_context(deadline uint64, networkPtr, networkLen, addressPtr, addressLen, connIDPtr uint32) uint64

//go:wasmimport net conn_get_buffer_ptr
func conn_get_buffer_ptr(connID uint64, bufferPtrPtr uint32) uint64

//go:wasmimport net conn_get_write_buffer_ptr
func conn_get_write_buffer_ptr(connID uint64, bufferPtrPtr uint32) uint64

//go:wasmimport net conn_close
func conn_close(connID uint64) uint64

//go:wasmimport net conn_set_read_deadline
func conn_set_read_deadline(connID uint64, deadline uint64) uint64

//go:wasmimport net conn_set_write_deadline
func conn_set_write_deadline(connID uint64, deadline uint64) uint64

//go:wasmimport net conn_set_deadline
func conn_set_deadline(connID uint64, deadline uint64) uint64

//go:wasmimport net conn_remote_addr
func conn_remote_addr(connID uint64, addrPtr, addrLenPtr uint32) uint64

//go:wasmimport net conn_local_addr
func conn_local_addr(connID uint64, addrPtr, addrLenPtr uint32) uint64

//go:wasmimport net conn_dial_tls_with_config
func conn_dial_tls_with_config(networkPtr, networkLen, addressPtr, addressLen, configPtr, configLen, connIDPtr uint32) uint64

//go:wasmimport net conn_tls_handshake
func conn_tls_handshake(connID uint64) uint64

//go:wasmimport net listener_listen
func listener_listen(networkPtr, networkLen, addressPtr, addressLen, listenerIDPtr uint32) uint64

//go:wasmimport net listener_accept
func listener_accept(listenerID uint64, connIDPtr uint32) uint64

//go:wasmimport net listener_serve_start
func listener_serve_start(listenerID uint64, callbackFuncPtr, callbackFuncLen uint32) uint64

//go:wasmimport net listener_close
func listener_close(listenerID uint64) uint64

//go:wasmimport net listener_addr
func listener_addr(listenerID uint64, addrPtr, addrLenPtr uint32) uint64
