//go:build !wasip1

// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.
package http

// StopServerByID останавливает HTTP сервер по его ID.
// В не-WASM окружении не реализовано, так как сервер управляется стандартным способом.
func StopServerByID(serverID uint64) (err error) {

	// В не-WASM окружении сервер управляется стандартным способом
	return
}
