//go:build !wasip1

// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.
package http

import (
	"context"
	"net"
	"net/http"
)

// NewTransport создаёт новый http.Transport, использующий стандартный net.Dial.
func NewTransport() (transport *http.Transport) {

	return &http.Transport{
		DialContext: func(ctx context.Context, network, addr string) (conn net.Conn, err error) {
			dialer := &net.Dialer{}
			return dialer.DialContext(ctx, network, addr)
		},
	}
}

// NewClient создаёт новый http.Client с Transport, использующим стандартный net.Dial.
func NewClient() (client *http.Client) {

	return &http.Client{
		Transport: NewTransport(),
	}
}
