//go:build wasip1

// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.
package http

//go:wasmimport net host_listen_and_serve
func hostListenAndServe(addrPtr uint32, addrLen uint32, handlerID uint64) (result uint64)

//go:wasmimport net host_get_next_request
func hostGetNextRequest(requestIDPtr uint32, handlerIDPtr uint32) (result uint64)

//go:wasmimport net host_get_request_info
func hostGetRequestInfo(requestID uint64, infoBufPtr uint32, infoBufLen uint32) (result uint64)

//go:wasmimport net host_read_request_body
func hostReadRequestBody(requestID uint64, bufPtr uint32, bufLen uint32) (result uint64)

//go:wasmimport net host_write_response_headers
func hostWriteResponseHeaders(requestID uint64, statusCode int32, headersPtr uint32, headersLen uint32) (result uint64)

//go:wasmimport net host_write_response_body
func hostWriteResponseBody(requestID uint64, dataPtr uint32, dataLen uint32) (result uint64)

//go:wasmimport net host_finish_request
func hostFinishRequest(requestID uint64) (result uint64)

//go:wasmimport net host_stop_server
func hostStopServer(serverID uint64) (result uint64)
