// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.
package i18n

import (
	"os"
	"strings"
	"sync"
)

const (
	langDir    = "lang"
	langCodeEN = "en"
	envLang    = "TG_LANG"
)

var (
	detectedLanguage   string
	detectLanguageOnce sync.Once
)

func GetLang() (lang string) {
	detectLanguageOnce.Do(func() {
		if detectedLanguage = strings.ToLower(strings.TrimSpace(os.Getenv(envLang))); detectedLanguage != "" {
			return
		}
		detectedLanguage = langCodeEN
	})
	return detectedLanguage
}
