//go:build wasip1

// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.
package net

// NewConnFromID создаёт новое соединение из connID.
// Используется для обработки входящих соединений от listener.
func NewConnFromID(connID uint64) (conn *Conn) {

	return &Conn{
		id:      connID,
		network: NetworkTCP,
	}
}
