//go:build wasip1

// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.

package wasm

var initGeneratorGenerateFunc func(rootDir string, moduleName string) (err error)
var initGeneratorCleanupFunc func(rootDir string) (err error)

// SetInitGeneratorInstance сохраняет экземпляр генератора для экспорта через WASM.
func SetInitGeneratorInstance(generateFunc func(rootDir string, moduleName string) (err error), cleanupFunc func(rootDir string) (err error)) {

	initGeneratorGenerateFunc = generateFunc
	initGeneratorCleanupFunc = cleanupFunc
}

// generateRequest — параметры для generate (rootDir, moduleName).
type generateRequest struct {
	RootDir    string `json:"rootDir"`
	ModuleName string `json:"moduleName"`
}

// generateResponse — ошибка при генерации (если есть).
type generateResponse struct {
	Error string `json:"error,omitempty"`
}

// cleanupRequest — параметр rootDir для очистки.
type cleanupRequest struct {
	RootDir string `json:"rootDir"`
}

// cleanupResponse — ошибка при очистке (если есть).
type cleanupResponse struct {
	Error string `json:"error,omitempty"`
}

// generateHandler вызывает initGeneratorGenerateFunc; для WASM вызывается из export.
func generateHandler(req generateRequest) (resp generateResponse, err error) {

	if initGeneratorGenerateFunc == nil {
		return generateResponse{}, nil
	}

	if err = initGeneratorGenerateFunc(req.RootDir, req.ModuleName); err != nil {
		resp.Error = err.Error()
		return
	}

	return
}

// cleanupHandler вызывает initGeneratorCleanupFunc; для WASM вызывается из export.
func cleanupHandler(req cleanupRequest) (resp cleanupResponse, err error) {

	if initGeneratorCleanupFunc == nil {
		return cleanupResponse{}, nil
	}

	if err = initGeneratorCleanupFunc(req.RootDir); err != nil {
		resp.Error = err.Error()
		return
	}

	return
}

// GenerateExported — go:wasmexport generate; обёртка для вызова из хоста.
//
//go:wasmexport generate
func GenerateExported(ptr uint32, size uint32) (result uint64) {

	return exportWrapper(generateHandler)(ptr, size)
}

// CleanupExported — go:wasmexport cleanup; обёртка для вызова из хоста.
//
//go:wasmexport cleanup
func CleanupExported(ptr uint32, size uint32) (result uint64) {

	return exportWrapper(cleanupHandler)(ptr, size)
}
