//go:build wasip1

// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.

package wasm

// HandleHostError обрабатывает uint64 результат от host функции
// и возвращает ошибку, если она есть.
// Формат результата: верхние 32 бита - указатель, нижние 32 бита - размер (31-й бит - флаг ошибки).
func HandleHostError(result uint64) (err error) {

	if result == 0 {
		return nil
	}

	return retUint64ToError(result)
}

// createErrorResultFromBytes создает uint64 результат с ошибкой из байтов.
func createErrorResultFromBytes(errBytes []byte) (result uint64) {

	if len(errBytes) == 0 {
		return 0
	}

	errorPtr, errorSize := byteToPtr(errBytes)
	if errorPtr == 0 {
		return (uint64(0) << 32) | (uint64(0) | (1 << 31))
	}

	return (uint64(errorPtr) << 32) | (uint64(errorSize) | (1 << 31))
}

// createSuccessResult создает uint64 результат без ошибки.
// Формат: верхние 32 бита - указатель на данные, нижние 32 бита - размер.
func createSuccessResult(ptr uint32, size uint32) (result uint64) {

	return (uint64(ptr) << 32) | uint64(size)
}
