//go:build wasip1

// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.

package wasm

import (
	"github.com/goccy/go-json"
)

// executeRequest представляет запрос на выполнение плагина.
type executeRequest struct {
	Request json.RawMessage `json:"request"`
}

// executeResponse представляет ответ на выполнение плагина.
type executeResponse struct {
	Error    string `json:"error,omitempty"`
	Response any    `json:"response,omitempty"`
}

// infoResponse представляет ответ с информацией о плагине.
type infoResponse struct {
	Info json.RawMessage `json:"info"`
}

// taskResponse представляет ответ от хоста при работе с задачами.
type taskResponse struct {
	Error    string          `json:"error,omitempty"`
	Response json.RawMessage `json:"response,omitempty"`
}

// CommandResponse представляет результат выполнения команды через хост.
// Stdout и Stderr передаются через потоки (streamID), а не кодируются.
type CommandResponse struct {
	ExitCode       int    `json:"exitCode"`
	StdoutStreamID int32  `json:"stdoutStreamID,omitempty"`
	StderrStreamID int32  `json:"stderrStreamID,omitempty"`
	Error          string `json:"error,omitempty"`
}

// interactiveSelectConfig представляет конфигурацию интерактивного выбора.
type interactiveSelectConfig struct {
	Prompt         string   `json:"prompt"`
	Options        []string `json:"options"`
	MultiSelect    bool     `json:"multiSelect"`
	DefaultOptions []string `json:"defaultOptions"`
}

// interactiveSelectResponse представляет ответ интерактивного выбора.
type interactiveSelectResponse struct {
	Selected []any `json:"selected"` // Может быть []string после преобразования
}
