//go:build wasip1

// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.

package wasm

var initGeneratorGenerateFunc func(rootDir string, moduleName string) (err error)
var initGeneratorCleanupFunc func(rootDir string) (err error)

// SetInitGeneratorInstance устанавливает экземпляр генератора для plugin init.
func SetInitGeneratorInstance(
	generateFunc func(rootDir string, moduleName string) (err error),
	cleanupFunc func(rootDir string) (err error),
) {

	initGeneratorGenerateFunc = generateFunc
	initGeneratorCleanupFunc = cleanupFunc
}

// generateRequest представляет запрос на генерацию кода.
type generateRequest struct {
	RootDir    string `json:"rootDir"`
	ModuleName string `json:"moduleName"`
}

// generateResponse представляет ответ на генерацию кода.
type generateResponse struct {
	Error string `json:"error,omitempty"`
}

// cleanupRequest представляет запрос на очистку сгенерированных файлов.
type cleanupRequest struct {
	RootDir string `json:"rootDir"`
}

// cleanupResponse представляет ответ на очистку.
type cleanupResponse struct {
	Error string `json:"error,omitempty"`
}

// generateHandler обрабатывает запрос на генерацию кода.
func generateHandler(req generateRequest) (resp generateResponse, err error) {

	if initGeneratorGenerateFunc == nil {
		return generateResponse{}, nil
	}

	if err = initGeneratorGenerateFunc(req.RootDir, req.ModuleName); err != nil {
		resp.Error = err.Error()
		return resp, nil
	}

	return resp, nil
}

// cleanupHandler обрабатывает запрос на очистку сгенерированных файлов.
func cleanupHandler(req cleanupRequest) (resp cleanupResponse, err error) {

	if initGeneratorCleanupFunc == nil {
		return cleanupResponse{}, nil
	}

	if err = initGeneratorCleanupFunc(req.RootDir); err != nil {
		resp.Error = err.Error()
		return resp, nil
	}

	return resp, nil
}

// GenerateExported обертка для экспорта функции generate через WASM.
//
//go:wasmexport generate
func GenerateExported(ptr uint32, size uint32) (result uint64) {

	return exportWrapper(generateHandler)(ptr, size)
}

// CleanupExported обертка для экспорта функции cleanup через WASM.
//
//go:wasmexport cleanup
func CleanupExported(ptr uint32, size uint32) (result uint64) {

	return exportWrapper(cleanupHandler)(ptr, size)
}
