//go:build !wasip1

// Code generated by 'T'ool 'G'ateway. DO NOT EDIT.

package wasm

// Для не-WASM сборок заглушка: экземпляр генератора не сохраняется.
func SetInitGeneratorInstance(generateFunc func(rootDir string, moduleName string) (err error), cleanupFunc func(rootDir string) (err error)) {
}
