//go:build wasip1

// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.

package wasm

import (
	"time"
)

// AdaptivePollingRead выполняет адаптивный polling с проверкой готовности для чтения.
// checkFunc - функция проверки готовности, возвращает (ready, n, error).
// deadline - время истечения ожидания (может быть нулевым).
// Возвращает количество прочитанных/записанных байт и ошибку при истечении deadline или при ошибке checkFunc.
func AdaptivePollingRead(checkFunc func() (ready bool, n int, err error), deadline time.Time) (n int, err error) {

	checkInterval := time.Millisecond * 5
	maxInterval := time.Millisecond * 100
	consecutiveEmpty := 0

	for {
		ready, readN, checkErr := checkFunc()
		if checkErr != nil {
			return readN, checkErr
		}

		if ready {
			// Успешное чтение/запись
			return readN, nil
		}

		// Проверяем deadline перед блокировкой
		if !deadline.IsZero() {
			if time.Now().After(deadline) {
				return 0, &timeoutError{msg: "deadline exceeded"}
			}

			remaining := time.Until(deadline)
			if remaining <= 0 {
				return 0, &timeoutError{msg: "deadline exceeded"}
			}

			// Используем минимальное время из оставшегося до deadline и текущего интервала
			if remaining < checkInterval {
				checkInterval = remaining
			}
		}

		// Адаптивный интервал: увеличиваем при отсутствии данных/места
		consecutiveEmpty++
		if consecutiveEmpty > 5 {
			// Удваиваем интервал, но не больше максимума
			newInterval := checkInterval * 2
			if newInterval > maxInterval {
				checkInterval = maxInterval
			} else {
				checkInterval = newInterval
			}
		}

		// Блокируем на адаптивный интервал
		// Это позволяет горутинам на хосте записать/прочитать данные в/из кольцевого буфера
		// В WASM нет настоящих горутин, поэтому используем time.Sleep
		time.Sleep(checkInterval)
	}
}

// timeoutError представляет ошибку timeout при чтении/записи.
type timeoutError struct {
	msg string
}

func (e *timeoutError) Error() (msg string) {

	return e.msg
}

func (e *timeoutError) Timeout() (isTimeout bool) {

	return true
}

func (e *timeoutError) Temporary() (isTemporary bool) {

	return true
}
