//go:build wasip1

// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.

package wasm

import (
	"context"
	"fmt"
	"log/slog"

	"github.com/goccy/go-json"
)

// logMessage представляет структуру JSON сообщения лога.
type logMessage struct {
	Level   string         `json:"level"` // Уровень логирования как строка: "debug", "info", "warn", "error"
	Message string         `json:"message"`
	Attrs   map[string]any `json:"attrs,omitempty"`
}

// hostLog выводит сообщение в лог через host_log.
//
//go:wasmimport env host_log
func hostLog(msgPtr uint32, msgLen uint32)

// hostLoggerHandler реализует slog.Handler для WASM окружения.
type hostLoggerHandler struct{}

// Enabled проверяет, включён ли указанный уровень логирования.
func (h *hostLoggerHandler) Enabled(ctx context.Context, level slog.Level) (enabled bool) {

	return true
}

// Handle обрабатывает запись лога.
func (h *hostLoggerHandler) Handle(ctx context.Context, record slog.Record) (err error) {

	// Преобразуем slog.Level в строку
	var levelStr string
	switch record.Level {
	case slog.LevelDebug:
		levelStr = "debug"
	case slog.LevelInfo:
		levelStr = "info"
	case slog.LevelWarn:
		levelStr = "warn"
	case slog.LevelError:
		levelStr = "error"
	default:
		levelStr = "info"
	}

	// Собираем атрибуты
	attrs := make(map[string]any)
	record.Attrs(func(a slog.Attr) bool {
		value := a.Value.Any()
		if err, ok := value.(error); ok && err != nil {
			attrs[a.Key] = err.Error()
		} else {
			attrs[a.Key] = value
		}
		return true
	})

	// Формируем сообщение
	msg := logMessage{
		Level:   levelStr,
		Message: record.Message,
		Attrs:   attrs,
	}

	// Сериализуем в JSON
	msgBytes, err := json.Marshal(msg)
	if err != nil {
		// Если не удалось закодировать, отправляем простое сообщение
		msgBytes = []byte(fmt.Sprintf(`{"level":"%s","message":"%s"}`, levelStr, record.Message))
	}

	// Выделяем память и отправляем в хост
	msgPtr, msgLen := byteToPtr(msgBytes)
	if msgPtr == 0 {
		return nil
	}
	defer Free(msgPtr)

	hostLog(msgPtr, msgLen)

	return nil
}

// WithAttrs возвращает новый handler с дополнительными атрибутами.
func (h *hostLoggerHandler) WithAttrs(attrs []slog.Attr) (handler slog.Handler) {

	return h
}

// WithGroup возвращает новый handler с группой атрибутов.
func (h *hostLoggerHandler) WithGroup(name string) (handler slog.Handler) {

	return h
}

// InitLogger инициализирует дефолтный slog с handler, использующим hostLog.
func InitLogger() {

	handler := &hostLoggerHandler{}
	slog.SetDefault(slog.New(handler))
}
