//go:build !wasip1

// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.

package wasm

// InitLogger инициализирует дефолтный slog для не-WASM сборок.
// Для обычной платформы ничего не делает, используется стандартный slog.
func InitLogger() {

	// Для не-WASM сборок ничего не делаем, используется стандартный slog
}
