//go:build !wasip1

// GENERATED BY 'T'ool 'G'ateway. DO NOT EDIT.

package wasm

// SetInitGeneratorInstance устанавливает экземпляр генератора для plugin init.
// Для не-WASM сборок ничего не делает.
func SetInitGeneratorInstance(
	generateFunc func(rootDir string, moduleName string) (err error),
	cleanupFunc func(rootDir string) (err error),
) {

	// Для не-WASM сборок ничего не делаем
}
