// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	logrus "github.com/sirupsen/logrus"
	"os"
)

type withErrorCode interface {
	Code() int
}

type strError string

func (e strError) Error() string {
	return string(e)
}

func ExitOnError(log logrus.FieldLogger, err error, msg string) {
	if err != nil {
		log.WithError(err).Error(msg)
		os.Exit(1)
	}
}
