// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

type requestExampleRPCTest struct {
	Arg0 int           `json:"arg0"`
	Arg1 string        `json:"arg1"`
	Opts []interface{} `json:"opts"` // This field was defined with ellipsis (...).
}

type responseExampleRPCTest struct {
	Ret1 int    `json:"ret1"`
	Ret2 string `json:"ret2"`
}
