// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/seniorGolang/tg/v2/example/interfaces"
)

type ExampleRPCTest func(ctx context.Context, arg0 int, arg1 string, opts ...interface{}) (ret1 int, ret2 string, err error)

type MiddlewareExampleRPC func(next interfaces.ExampleRPC) interfaces.ExampleRPC

type MiddlewareExampleRPCTest func(next ExampleRPCTest) ExampleRPCTest
