// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"fmt"
	"github.com/gofiber/fiber/v2"
	"github.com/pkg/errors"
	log "github.com/rs/zerolog/log"
)

func (srv *Server) setLogger(ctx *fiber.Ctx) error {
	ctx.SetUserContext(srv.log.WithContext(ctx.UserContext()))
	return ctx.Next()
}

func recoverHandler(ctx *fiber.Ctx) error {
	defer func() {
		if r := recover(); r != nil {
			err, ok := r.(error)
			if !ok {
				err = errors.New(fmt.Sprintf("%v", r))
			}
			log.Ctx(ctx.UserContext()).Error().Stack().Err(errors.Wrap(err, "recover")).Str("method", ctx.Method()).Str("path", ctx.OriginalURL()).Msg("panic occurred")
			ctx.Status(fiber.StatusInternalServerError)
		}
	}()
	return ctx.Next()
}
