// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"io/ioutil"
	"mime/multipart"

	"github.com/gofiber/fiber/v2"
)

type cookieType interface {
	Cookie() *fiber.Cookie
}

func uploadFile(ctx *fiber.Ctx, key string) (data []byte, err error) {
	var fileHeader *multipart.FileHeader
	if fileHeader, err = ctx.FormFile(key); err != nil {
		return
	}
	var file multipart.File
	if file, err = fileHeader.Open(); err != nil {
		return
	}
	defer file.Close()
	return ioutil.ReadAll(file)
}
