// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"io/ioutil"
	"mime/multipart"

	"github.com/valyala/fasthttp"
)

type cookieType interface {
	Cookie() *fasthttp.Cookie
}

func uploadFile(ctx *fasthttp.RequestCtx, key string) (data []byte, err error) {

	var fileHeader *multipart.FileHeader
	if fileHeader, err = ctx.FormFile(key); err != nil {
		return
	}

	var file multipart.File
	if file, err = fileHeader.Open(); err != nil {
		return
	}
	defer file.Close()
	return ioutil.ReadAll(file)
}
