// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/seniorGolang/tg/example/interfaces"
)

type JsonRPCTest func(ctx context.Context, arg0 int, arg1 string, opts ...interface{}) (ret1 int, ret2 string, err error)

type MiddlewareJsonRPC func(next interfaces.JsonRPC) interfaces.JsonRPC

type MiddlewareJsonRPCTest func(next JsonRPCTest) JsonRPCTest
