// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/rs/zerolog"

	"github.com/seniorGolang/tg/example/interfaces"
)

type serverJsonRPC struct {
	svc  interfaces.JsonRPC
	test JsonRPCTest
}

type MiddlewareSetJsonRPC interface {
	Wrap(m MiddlewareJsonRPC)
	WrapTest(m MiddlewareJsonRPCTest)

	WithTrace()
	WithMetrics()
	WithLog(log zerolog.Logger)
}

func newServerJsonRPC(svc interfaces.JsonRPC) *serverJsonRPC {
	return &serverJsonRPC{
		svc:  svc,
		test: svc.Test,
	}
}

func (srv *serverJsonRPC) Wrap(m MiddlewareJsonRPC) {
	srv.svc = m(srv.svc)
	srv.test = srv.svc.Test
}

func (srv *serverJsonRPC) Test(ctx context.Context, arg0 int, arg1 string, opts ...interface{}) (ret1 int, ret2 string, err error) {
	return srv.test(ctx, arg0, arg1, opts...)
}

func (srv *serverJsonRPC) WrapTest(m MiddlewareJsonRPCTest) {
	srv.test = m(srv.test)
}

func (srv *serverJsonRPC) WithTrace() {
	srv.Wrap(traceMiddlewareJsonRPC)
}

func (srv *serverJsonRPC) WithMetrics() {
	srv.Wrap(metricsMiddlewareJsonRPC)
}

func (srv *serverJsonRPC) WithLog(log zerolog.Logger) {
	srv.Wrap(loggerMiddlewareJsonRPC(log))
}
