// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"github.com/gofiber/adaptor/v2"
	"github.com/gofiber/fiber/v2"
	prometheus "github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"github.com/rs/zerolog"
)

var VersionGauge *prometheus.GaugeVec
var RequestCount *prometheus.CounterVec
var RequestCountAll *prometheus.CounterVec
var RequestLatency *prometheus.HistogramVec

func (srv *Server) ServeMetrics(log zerolog.Logger, path string, address string) {
	srv.srvMetrics = fiber.New(fiber.Config{DisableStartupMessage: true})
	srv.srvMetrics.All(path, adaptor.HTTPHandler(promhttp.Handler()))
	go func() {
		err := srv.srvMetrics.Listen(address)
		ExitOnError(log, err, "serve metrics on "+address)
	}()
}
