// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import "github.com/valyala/fasthttp"

type Option func(srv *httpServer)

type Handler = fasthttp.RequestHandler
type ErrorHandler func(err error) error

func AfterHTTP(handler Handler) Option {
	return func(srv *httpServer) {
		srv.httpAfter = append(srv.httpAfter, handler)
	}
}

func BeforeHTTP(handler Handler) Option {
	return func(srv *httpServer) {
		srv.httpBefore = append(srv.httpBefore, handler)
	}
}

func ErrorHandle(handler ErrorHandler) Option {
	return func(srv *httpServer) {
		srv.errorHandler = handler
	}
}

func MaxBodySize(max int) Option {
	return func(srv *httpServer) {
		srv.maxRequestBodySize = max
	}
}
