// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import "github.com/seniorGolang/json"

func toString(value interface{}) string {
	data, _ := json.Marshal(value)
	return string(data)
}
