// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import "github.com/seniorGolang/tg/v2/example/interfaces/types"

type requestUserGetUser struct {
	Cookie    string `json:"cookie"`
	UserAgent string `json:"userAgent"`
}

type responseUserGetUser struct {
	User *types.User `json:"user"`
}

type requestUserCustomResponse struct {
	Arg0 int           `json:"arg0"`
	Arg1 string        `json:"arg1"`
	Opts []interface{} `json:"opts"` // This field was defined with ellipsis (...).
}

// Formal exchange type, please do not delete.
type responseUserCustomResponse struct{}

type requestUserCustomHandler struct {
	Arg0 int           `json:"arg0"`
	Arg1 string        `json:"arg1"`
	Opts []interface{} `json:"opts"` // This field was defined with ellipsis (...).
}

// Formal exchange type, please do not delete.
type responseUserCustomHandler struct{}
