// Copyright (c) 2020 Khramtsov Aleksei (contact@altsoftllc.com).
// This file (constants.go at 19.06.2020, 16:08) is subject to the terms and
// conditions defined in file 'LICENSE', which is part of this project source code.
package generator

const (
	packageOS                    = "os"
	packageIO                    = "io"
	_ctx_                        = "ctx"
	packageFmt                   = "fmt"
	packageTime                  = "time"
	_next_                       = "next"
	packageSync                  = "sync"
	packageTesting               = "testing"
	packageReflect               = "reflect"
	packageHttp                  = "net/http"
	packageContext               = "context"
	packageStrconv               = "strconv"
	packageStrings               = "strings"
	packageIOUtil                = "io/ioutil"
	packageJson                  = "encoding/json"
	packageMultipart             = "mime/multipart"
	packageCors                  = "github.com/lab259/cors"
	packageUUID                  = "github.com/google/uuid"
	packageFiber                 = "github.com/gofiber/fiber/v2"
	packageZeroLog               = "github.com/rs/zerolog"
	packageGoKitMetrics          = "github.com/go-kit/kit/metrics"
	packageGoKitEndpoint         = "github.com/go-kit/kit/endpoint"
	packageOpenZipkin            = "github.com/openzipkin/zipkin-go"
	packageViewer                = "github.com/seniorGolang/dumper/viewer"
	packageJaegerMetrics         = "github.com/uber/jaeger-lib/metrics"
	packageJaegerClient          = "github.com/uber/jaeger-client-go"
	packageJaegerLog             = "github.com/uber/jaeger-client-go/log"
	packageOpentracing           = "github.com/opentracing/opentracing-go"
	packageJaegerConfig          = "github.com/uber/jaeger-client-go/config"
	packageKitPrometheus         = "github.com/go-kit/kit/metrics/prometheus"
	packageOpentracingExt        = "github.com/opentracing/opentracing-go/ext"
	packageFiberAdaptor          = "github.com/gofiber/adaptor/v2"
	packageZipkinHttp            = "github.com/openzipkin/zipkin-go/reporter/http"
	packageStdPrometheus         = "github.com/prometheus/client_golang/prometheus"
	packageOpenZipkinOpenTracing = "github.com/openzipkin-contrib/zipkin-go-opentracing"
	packagePrometheusHttp        = "github.com/prometheus/client_golang/prometheus/promhttp"
)
